# Generated by Django 4.2 on 2024-12-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='title',
            field=models.CharField(default='default title', max_length=120),
            preserve_default=False,
        ),
    ]
