# Generated by Django 4.2 on 2024-12-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_capital_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='body',
            field=models.TextField(default='default body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capital',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
